{{- if and .Values.serviceAccount.create .Values.secretName -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mas-core.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "mas-core.labels" . | nindent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
