{{- $name := "masauto-operator" }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  channel: {{ .Values.channel | default "alpha" }}
  installPlanApproval: Automatic
  name: {{ $name }}
  source: {{ .Values.catalogName | default "ecosystem-engineering-catalog" }}
  sourceNamespace: {{ .Values.catalogNamespace | default "openshift-marketplace" }}
